name: skillsapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  circular_countdown_timer: ^0.2.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  http: ^1.3.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/logos/
    - assets/
  fonts:
    - family: bebasNeue
      fonts:
        - asset: 'assets/fonts/bebasNeue.otf'
    - family: frutiger
      fonts:
          - asset: 'assets/fonts/FrutigerLTStd-Light.otf'
          - asset: 'assets/fonts/FrutigerLTStd-Bold.otf'
          - asset: 'assets/fonts/FrutigerLTStd-Lightitalic.otf'
          - asset: 'assets/fonts/FrutigerLTStd-Roman.otf'
